version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: app-nginx
    ports:
      - "8090:8090"
      - "443:443"
    volumes:
      - ./:/var/www
    environment:
      - NGINX_CONF_PATH=/path/to/your/custom/default.conf  # Путь к кастомному файлу конфигурации Nginx
  db:
    platform: linux/x86_64
    image: mysql:5.6.47
    container_name: app-db
    ports:
      - "3306:3306"
    volumes:
      - ./etc/infrastructure/mysql/my.cnf:/etc/mysql/my.cnf
      - ./etc/database/base.sql:/docker-entrypoint-initdb.d/base.sql
  # Новый сервис PHP-FPM
  php:
    image: php:8.1-fpm
    container_name: app-php
    volumes:
      - ./:/var/www  # Монтирование текущей директории на контейнер

networks:
  my-network:  # Создание общей сети для всех сервисов
